### ISSUE TITLE
revdep in lubridate failure

### ISSUE THREAD

**Issue by vspinu** [davidcarslaw/openair#120]
Hi David,

I am preparing a new CRAN release of lubridate, which comes with stricter checks for invalid timezones, and your package showed up with this error:

```R
  Running examples in ‘openair-Ex.R’ failed
  The error most likely occurred in:
  
  > ### Name: selectByDate
  > ### Title: Subset a data frame based on date
  > ### Aliases: selectByDate
  > ### Keywords: methods
  > 
  > ### ** Examples
  > 
  > 
  > ## select all of 1999
  > data.1999 <- selectByDate(mydata, start = "1/1/1999", end = "31/12/1999")
  Warning: All formats failed to parse. No formats found.
  Warning: All formats failed to parse. No formats found.
  Error in C_force_tz(time, tz = tzone, roll) : 
    CCTZ: Unrecognized output timezone: "%d/%m/%Y"
  Calls: selectByDate ... >=.Date -> date_to_posix -> force_tz -> C_force_tz -> .Call
  Execution halted
```

Looks like either there is some sort of conflict of lubridate's `as_date` with some other package, or you are passing a format argument as `tz` to lubridate's `as_date`. In either case it should be easy to fix, I would guess.

**Comment by davidcarslaw** [comment]
Thanks Vitalie. Should be fixed now in openair. I will push to CRAN in the next couple of weeks...

**Comment by vspinu** [comment]
Thanks David!

**Comment by bjsilver** [comment]
Hi, I am still getting this error with the same example as provided. Has this been updated yet?
